# MPFR external project -*- CMake -*-
#
# Copyright (C) 2012 Guofu Xiang <gfxiang@gmail.com>.
# All rights reserved.

set(MPFR_GIT_REPOSITORY https://github.com/gx/mpfr.git)

set(MPFR_SOURCE_DIR "${CMAKE_CURRENT_BINARY_DIR}/mpfr")
set(MPFR_BINARY_DIR "${CMAKE_CURRENT_BINARY_DIR}/mpfr-build")
set(MPFR_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}")

configure_file(MPFRConfigureStep.cmake.in MPFRConfigureStep.cmake @ONLY)

set(MPFR_CONFIGURE_COMMAND
  ${CMAKE_COMMAND} -P ${CMAKE_CURRENT_BINARY_DIR}/MPFRConfigureStep.cmake)

ExternalProject_Add(mpfr
  SOURCE_DIR ${MPFR_SOURCE_DIR}
  BINARY_DIR ${MPFR_BINARY_DIR}
  INSTALL_DIR ${MPFR_INSTALL_DIR}
  GIT_REPOSITORY ${MPFR_GIT_REPOSITORY}
  UPDATE_COMMAND ""
  PATCH_COMMAND ""
  CONFIGURE_COMMAND ${MPFR_CONFIGURE_COMMAND})

# MPFR
set(MPFR_INCLUDE_DIR "${MPFR_INSTALL_DIR}/include")
set(MPFR_LIBRARY_DIR "${MPFR_INSTALL_DIR}/lib")
set(MPFR_LIBRARY "${MPFR_INSTALL_DIR}/lib/libmpfr${CMAKE_LINK_LIBRARY_SUFFIX}")

set(MPFR_INCLUDE_DIRS ${MPFR_INCLUDE_DIR} ${GMP_INCLUDE_DIRS})
set(MPFR_LIBRARY_DIRS ${MPFR_LIBRARY_DIR} ${GMP_LIBRARY_DIRS})
set(MPFR_LIBRARIES ${MPFR_LIBRARY} ${GMP_LIBRARIES})
